export type Review = {
  id: number;
  name: string;
  avatar: string;
  rating: number;
  text: string;
};

export type Dish = {
  id: number;
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  image: string;
  aiHint: string;
  price: number;
  ingredients: string[];
  category?: string;
  reviews: Review[];
};

export const dishes: Dish[] = [
  // Chinese
  {
    id: 1,
    slug: "chicken-hot-wings",
    name: "Chicken Hot Wings (6 pcs)",
    description: "Spicy and crispy fried chicken wings.",
    longDescription: "Six pieces of juicy chicken wings, battered, fried to a perfect crisp, and tossed in a fiery hot sauce. A perfect appetizer to kickstart your meal.",
    image: "https://www.foodfusion.com/wp-content/uploads/2017/04/1-1.jpg",
    aiHint: "hot wings",
    price: 600,
    ingredients: ["Chicken Wings", "Flour", "Hot Sauce", "Spices"],
    category: "Chinese",
    reviews: [],
  },
  {
    id: 2,
    slug: 'chicken-shashlik',
    name: 'Chicken Shashlik',
    description: 'Skewered chicken and vegetables in a tangy gravy.',
    longDescription: 'Cubes of chicken, bell peppers, onions, and tomatoes are grilled on skewers and served with a sweet and tangy tomato-based gravy, usually over rice.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2019/04/Chicken-Shashlik-Recipe-by-Food-fusion-1.jpg',
    aiHint: 'chicken shashlik',
    price: 600,
    ingredients: ['Chicken', 'Bell Peppers', 'Onion', 'Tomato', 'Ketchup'],
    category: 'Chinese',
    reviews: [],
  },
  {
    id: 3,
    slug: 'chicken-chow-mein',
    name: 'Chicken Chowmein',
    description: 'Stir-fried noodles with chicken and vegetables.',
    longDescription: 'A classic noodle dish with stir-fried egg noodles, tender chicken strips, and a variety of vegetables like cabbage, carrots, and bell peppers in a savory sauce.',
    image: 'https://i.ytimg.com/vi/bYf66g5g3c4/maxresdefault.jpg',
    aiHint: 'chicken chow mein',
    price: 600,
    ingredients: ['Noodles', 'Chicken', 'Cabbage', 'Carrots', 'Soy Sauce'],
    category: 'Chinese',
    reviews: [],
  },
  {
    id: 4,
    slug: 'chicken-panini-pasta-family',
    name: 'Chicken Panini Pasta (3 persons)',
    description: 'Creamy white garlic sauce pasta for three.',
    longDescription: 'A family-sized portion of delicious panini pasta tossed in a creamy white garlic sauce with tender pieces of chicken. Perfect for sharing.',
    image: 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'chicken pasta family',
    price: 1600,
    ingredients: ["Pasta", "Chicken", "Garlic", "Cream", "Herbs"],
    category: "Chinese",
    reviews: [],
  },
  {
    id: 5,
    slug: 'chicken-panini-pasta-single',
    name: 'Chicken Panini Pasta (Single)',
    description: 'Creamy white garlic sauce pasta for one.',
    longDescription: 'A single serving of our delicious panini pasta tossed in a creamy white garlic sauce with tender pieces of chicken.',
    image: 'https://images.pexels.com/photos/1256875/pexels-photo-1256875.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'chicken pasta single',
    price: 600,
    ingredients: ["Pasta", "Chicken", "Garlic", "Cream", "Herbs"],
    category: "Chinese",
    reviews: [],
  },
  {
    id: 6,
    slug: 'chicken-spicy-spaghetti-family',
    name: 'Chicken Spicy Spaghetti (3 persons)',
    description: 'Spicy spaghetti with chicken and vegetables for three.',
    longDescription: 'A generous portion of spicy spaghetti tossed with vegetables and chicken, perfect for a group of three. A fiery and flavorful meal.',
    image: 'https://images.pexels.com/photos/1487511/pexels-photo-1487511.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'spicy spaghetti family',
    price: 1600,
    ingredients: ["Spaghetti", "Chicken", "Vegetables", "Chili Sauce", "Spices"],
    category: "Chinese",
    reviews: [],
  },
  {
    id: 7,
    slug: 'chicken-spicy-spaghetti-single',
    name: 'Chicken Spicy Spaghetti (Single)',
    description: 'Spicy spaghetti with chicken and vegetables for one.',
    longDescription: 'A single serving of our spicy spaghetti tossed with vegetables and chicken. A fiery and flavorful meal for one.',
    image: 'https://images.pexels.com/photos/1460872/pexels-photo-1460872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'spicy spaghetti single',
    price: 600,
    ingredients: ["Spaghetti", "Chicken", "Vegetables", "Chili Sauce", "Spices"],
    category: "Chinese",
    reviews: [],
  },
  {
    id: 8,
    slug: 'chicken-corn-soup-family',
    name: 'Chicken Corn Soup (4 servings)',
    description: 'A hearty and comforting soup for four.',
    longDescription: 'A classic comfort soup for the whole family, made with shredded chicken, sweet corn kernels, and egg ribbons in a thick, savory broth.',
    image: 'https://static.toiimg.com/thumb/56968498.cms?width=1200&height=900',
    aiHint: 'chicken corn soup',
    price: 1000,
    ingredients: ['Chicken', 'Sweet Corn', 'Egg', 'Chicken Broth', 'Soy Sauce'],
    category: 'Soup',
    reviews: [],
  },
   {
    id: 9,
    slug: 'chicken-corn-soup-single',
    name: 'Chicken Corn Soup (Single)',
    description: 'A hearty and comforting soup for one.',
    longDescription: 'A single serving of our classic comfort soup, made with shredded chicken, sweet corn kernels, and egg ribbons in a thick, savory broth.',
    image: 'https://www.kfoods.com/images1/newrecipeicon/chicken-corn-soup_23.jpg',
    aiHint: 'chicken corn soup single',
    price: 280,
    ingredients: ['Chicken', 'Sweet Corn', 'Egg', 'Chicken Broth', 'Soy Sauce'],
    category: 'Soup',
    reviews: [],
  },
  {
    id: 10,
    slug: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed rice with chicken, egg, and vegetables.',
    longDescription: 'A complete meal in a bowl, our Chicken Fried Rice is made with tender chicken pieces, scrambled eggs, and mixed vegetables, all stir-fried with rice and savory sauces.',
    image: 'https://www.masala.tv/wp-content/uploads/2022/04/fried-rice-2.jpg',
    aiHint: 'chicken fried rice',
    price: 450,
    ingredients: ['Rice', 'Chicken', 'Eggs', 'Vegetables', 'Soy Sauce'],
    category: 'Rice',
    reviews: [],
  },
  {
    id: 11,
    slug: 'egg-fried-rice',
    name: 'Egg Fried Rice',
    description: 'Classic fried rice with scrambled eggs and vegetables.',
    longDescription: 'A simple yet satisfying dish of stir-fried rice with scrambled eggs, carrots, peas, and a light touch of soy sauce.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2017/02/DSC_0152.jpg',
    aiHint: 'egg fried rice',
    price: 400,
    ingredients: ['Rice', 'Eggs', 'Carrots', 'Peas', 'Soy Sauce'],
    category: 'Rice',
    reviews: [],
  },
  // Fast Food
  {
    id: 12,
    slug: 'chicken-shawarma-medium',
    name: 'Chicken Shawarma (Medium)',
    description: 'A medium-sized wrap of succulent chicken.',
    longDescription: 'Tender, marinated chicken, shaved off a vertical rotisserie, wrapped in a soft pita bread with garlic sauce, pickles, and fries. The perfect medium-sized meal.',
    image: 'https://images.pexels.com/photos/8118671/pexels-photo-8118671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'chicken shawarma',
    price: 240,
    ingredients: ["Chicken", "Pita Bread", "Garlic Sauce", "Pickles"],
    category: "Fast Food",
    reviews: [],
  },
  {
    id: 13,
    slug: 'chicken-shawarma-large',
    name: 'Chicken Shawarma (Large)',
    description: 'A large-sized wrap of succulent chicken.',
    longDescription: 'A larger portion of our tender, marinated chicken, shaved off a vertical rotisserie, wrapped in a soft pita bread with garlic sauce, pickles, and fries.',
    image: 'https://images.pexels.com/photos/4038753/pexels-photo-4038753.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'large chicken shawarma',
    price: 350,
    ingredients: ["Chicken", "Pita Bread", "Garlic Sauce", "Pickles"],
    category: "Fast Food",
    reviews: [],
  },
  {
    id: 14,
    slug: 'anda-shami-burger',
    name: 'Anda Shami Burger',
    description: 'The classic Karachi-style street burger.',
    longDescription: 'A popular Pakistani street food burger featuring a shami kabab (spiced lentil and meat patty) and a fried egg, topped with chutney and onions in a soft bun.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2021/04/anda-shami.jpg',
    aiHint: 'anda shami burger',
    price: 200,
    ingredients: ["Shami Kabab", "Egg", "Bun", "Chutney", "Onion"],
    category: "Fast Food",
    reviews: [],
  },
  {
    id: 15,
    slug: 'chicken-zinger-burger',
    name: 'Chicken Zinger Burger',
    description: 'A crispy, spicy fried chicken fillet burger.',
    longDescription: 'A crunchy, spicy fried chicken fillet (zinger) served in a sesame seed bun with lettuce and mayonnaise. A satisfying and popular choice.',
    image: 'https://images.pexels.com/photos/13998968/pexels-photo-13998968.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'zinger burger',
    price: 600,
    ingredients: ["Chicken Fillet", "Bun", "Lettuce", "Mayonnaise", "Spices"],
    category: "Fast Food",
    reviews: [],
  },
  // Seafood
  {
    id: 16,
    slug: 'fry-fish-rohu',
    name: 'Fry Fish (Rohu) per kg',
    description: 'Crispy fried Rohu fish, sold by the kilogram.',
    longDescription: 'Rohu fish, marinated in traditional Lahori spices and coated in a crispy batter, then deep-fried. Price is per kilogram of pre-frying weight.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2018/11/Lahori-Fried-Fish-2-2.jpg',
    aiHint: 'fried fish',
    price: 1800,
    ingredients: ["Rohu Fish", "Gram Flour", "Spices", "Lemon"],
    category: "Seafood",
    reviews: [],
  },
  {
    id: 17,
    slug: 'bbq-fish-rohu',
    name: 'BBQ Fish (Rohu) per kg (N/A)',
    description: 'Barbecued Rohu fish, sold by the kilogram.',
    longDescription: 'Rohu fish marinated in a smoky BBQ rub and grilled over charcoal. Currently unavailable. Price is per kilogram of pre-frying weight.',
    image: 'https://www.kfoods.com/images1/newrecipeicon/Tandoori-Fish-Tikka_349.jpg',
    aiHint: 'bbq fish',
    price: 2000,
    ingredients: ["Rohu Fish", "BBQ Spices", "Yogurt", "Ginger-Garlic Paste"],
    category: "Seafood",
    reviews: [],
  },
  // Karahi & Handi
  {
    id: 18,
    slug: 'chicken-karahi-full',
    name: 'Chicken Karahi (Full)',
    description: 'Over 1kg of rich and spicy chicken karahi.',
    longDescription: 'A full portion (over 1kg) of the classic Pakistani dish, cooked with tomatoes, ginger, garlic, and green chilies in a traditional wok (karahi).',
    image: 'https://images.pexels.com/photos/18949576/pexels-photo-18949576/free-photo-of-indian-dish-in-bowl-on-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'chicken karahi',
    price: 2000,
    ingredients: ["Chicken", "Tomatoes", "Ginger", "Garlic", "Spices"],
    category: "Karahi",
    reviews: [],
  },
  {
    id: 19,
    slug: 'chicken-karahi-half',
    name: 'Chicken Karahi (Half)',
    description: 'A half portion of rich and spicy chicken karahi.',
    longDescription: 'A half portion (over 0.5kg) of the classic Pakistani dish, cooked with tomatoes, ginger, garlic, and green chilies in a traditional wok (karahi).',
    image: 'https://www.foodfusion.com/wp-content/uploads/2019/08/Chicken-Karahi-Recipe-by-Food-Fusion-1.jpg',
    aiHint: 'chicken karahi plate',
    price: 1100,
    ingredients: ["Chicken", "Tomatoes", "Ginger", "Garlic", "Spices"],
    category: "Karahi",
    reviews: [],
  },
  {
    id: 20,
    slug: 'chicken-boneless-handi-full',
    name: 'Chicken Boneless Handi (Full)',
    description: '1kg of creamy, boneless chicken handi.',
    longDescription: 'A full 1kg portion of boneless chicken pieces cooked in a creamy, tomato-based gravy in a traditional clay pot (handi).',
    image: 'https://www.foodfusion.com/wp-content/uploads/2019/11/Chicken-Handi-Recipe-by-food-fusion.jpg',
    aiHint: 'chicken handi',
    price: 2400,
    ingredients: ["Boneless Chicken", "Cream", "Yogurt", "Tomatoes", "Spices"],
    category: "Karahi",
    reviews: [],
  },
  {
    id: 21,
    slug: 'chicken-boneless-handi-half',
    name: 'Chicken Boneless Handi (Half)',
    description: 'A half portion of creamy, boneless chicken handi.',
    longDescription: 'A half portion of our boneless chicken pieces cooked in a creamy, tomato-based gravy in a traditional clay pot (handi).',
    image: 'https://images.pexels.com/photos/106343/pexels-photo-106343.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'chicken handi plate',
    price: 1300,
    ingredients: ["Boneless Chicken", "Cream", "Yogurt", "Tomatoes", "Spices"],
    category: "Karahi",
    reviews: [],
  },
  {
    id: 22,
    slug: 'chicken-white-boneless-handi-full',
    name: 'Chicken White Boneless Handi (Full)',
    description: '1kg of rich, white, creamy chicken handi.',
    longDescription: 'A full 1kg portion of boneless chicken cooked in a rich, creamy white sauce made with yogurt, cream, and delicate spices.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2021/04/white-chicken-handi.jpg',
    aiHint: 'white chicken handi',
    price: 2500,
    ingredients: ["Boneless Chicken", "Cream", "Yogurt", "White Pepper", "Cashews"],
    category: "Karahi",
    reviews: [],
  },
  {
    id: 23,
    slug: 'chicken-white-boneless-handi-half',
    name: 'Chicken White Boneless Handi (Half)',
    description: 'A half portion of rich, white, creamy chicken handi.',
    longDescription: 'A half portion of boneless chicken cooked in a rich, creamy white sauce made with yogurt, cream, and delicate spices.',
    image: 'https://www.masala.tv/wp-content/uploads/2020/02/white-chicken-karahi.jpg',
    aiHint: 'white chicken handi plate',
    price: 1350,
    ingredients: ["Boneless Chicken", "Cream", "Yogurt", "White Pepper", "Cashews"],
    category: "Karahi",
    reviews: [],
  },
  {
    id: 24,
    slug: 'beef-makhani-qeema-karahi-full',
    name: 'Beef Makhani Qeema Karahi (1kg)',
    description: 'Buttery and rich minced beef karahi.',
    longDescription: '1kg of finely minced beef (qeema) cooked in a buttery (makhani) and spicy karahi style. A rich and indulgent dish.',
    image: 'https://www.kfoods.com/images1/newrecipeicon/qeema-karahi_7110.jpg',
    aiHint: 'qeema karahi',
    price: 2600,
    ingredients: ["Minced Beef", "Butter", "Tomatoes", "Yogurt", "Spices"],
    category: "Karahi",
    reviews: [],
  },
  {
    id: 25,
    slug: 'beef-makhani-qeema-karahi-half',
    name: 'Beef Makhani Qeema Karahi (Half)',
    description: 'Half portion of buttery minced beef karahi.',
    longDescription: 'A half portion of our finely minced beef (qeema) cooked in a buttery (makhani) and spicy karahi style.',
    image: 'https://i.ytimg.com/vi/U3tGEp9RgxY/maxresdefault.jpg',
    aiHint: 'qeema karahi plate',
    price: 1400,
    ingredients: ["Minced Beef", "Butter", "Tomatoes", "Yogurt", "Spices"],
    category: "Karahi",
    reviews: [],
  },
  // BBQ
  {
    id: 26,
    slug: 'sajji-medium',
    name: 'Sajji (Medium)',
    description: 'Medium-sized whole roasted chicken.',
    longDescription: 'A whole chicken, marinated in mild spices and roasted to perfection. A Balochi delicacy known for its unique flavor.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2019/07/Chicken-Sajji-1.jpg',
    aiHint: 'chicken sajji',
    price: 1200,
    ingredients: ["Whole Chicken", "Salt", "Paprika", "Lemon"],
    category: "BBQ",
    reviews: [],
  },
  {
    id: 27,
    slug: 'sajji-large',
    name: 'Sajji (Large)',
    description: 'Large-sized whole roasted chicken.',
    longDescription: 'A large whole chicken, marinated in mild spices and roasted to perfection. A Balochi delicacy known for its unique flavor.',
    image: 'https://images.pexels.com/photos/6210876/pexels-photo-6210876.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'large chicken sajji',
    price: 1350,
    ingredients: ["Whole Chicken", "Salt", "Paprika", "Lemon"],
    category: "BBQ",
    reviews: [],
  },
  {
    id: 28,
    slug: 'chicken-chest-tikka',
    name: 'Chicken Tikka (Chest)',
    description: 'Tender chicken breast piece, marinated and grilled.',
    longDescription: 'A lighter but equally delicious option, the Chicken Chest Tikka is a boneless breast piece marinated in our signature spice mix and grilled until tender and flavorful.',
    image: 'https://images.pexels.com/photos/262959/pexels-photo-262959.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'chicken tikka breast',
    price: 370,
    ingredients: ['Chicken Breast', 'Yogurt', 'Tikka Masala', 'Lemon Juice', 'Spices'],
    category: 'BBQ',
    reviews: [],
  },
  {
    id: 29,
    slug: 'chicken-leg-tikka',
    name: 'Chicken Tikka (Leg)',
    description: 'Juicy chicken leg marinated in traditional spices and grilled to perfection.',
    longDescription: 'A classic BBQ favorite, our Chicken Leg Tikka features a whole chicken leg marinated in a blend of yogurt, lemon juice, and aromatic spices, then grilled over charcoal for a smoky flavor.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2019/04/Chicken-Tikka-Recipe-by-Food-Fusion-1.jpg',
    aiHint: 'chicken tikka leg',
    price: 350,
    ingredients: ['Chicken Leg', 'Yogurt', 'Tikka Masala', 'Lemon Juice', 'Ginger-Garlic Paste'],
    category: 'BBQ',
    reviews: [],
  },
  {
    id: 30,
    slug: 'chicken-boti',
    name: 'Chicken Malai/Regular Boti (4 pcs)',
    description: 'Your choice of creamy or spicy chicken cubes.',
    longDescription: 'One seekh with four pieces of boneless chicken. Choose between our creamy, mild Malai Boti or the spicy, traditional Tikka Boti.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2019/07/Chicken-Malai-Boti-Recipe-By-Food-Fusion-1.jpg',
    aiHint: 'chicken boti seekh',
    price: 200,
    ingredients: ["Boneless Chicken", "Yogurt", "Spices", "Cream"],
    category: "BBQ",
    reviews: [],
  },
  {
    id: 31,
    slug: 'chicken-dam-kabab',
    name: 'Chicken Dam/Smoked Kabab (6 pcs)',
    description: 'Smoky, steamed minced chicken kababs.',
    longDescription: 'Six pieces of minced chicken kababs, infused with a smoky aroma through the traditional "dam" technique. Incredibly moist and flavorful.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2020/12/gola-kabab.jpg',
    aiHint: 'chicken kabab',
    price: 550,
    ingredients: ["Minced Chicken", "Onion", "Herbs", "Spices", "Coal"],
    category: "BBQ",
    reviews: [],
  },
  {
    id: 32,
    slug: 'beef-dam-kabab',
    name: 'Beef Dam/Smoked Kabab (6 pcs)',
    description: 'Smoky, steamed minced beef kababs.',
    longDescription: 'Six pieces of minced beef kababs, infused with a smoky aroma through the traditional "dam" technique. Juicy, tender, and packed with flavor.',
    image: 'https://www.masala.tv/wp-content/uploads/2021/04/beef-seekh-kabab.jpg',
    aiHint: 'beef kabab',
    price: 700,
    ingredients: ["Minced Beef", "Onion", "Herbs", "Spices", "Coal"],
    category: "BBQ",
    reviews: [],
  },
  {
    id: 33,
    slug: 'beef-chapli-kabab',
    name: 'Beef Chapli Kabab',
    description: 'Peshawari-style flat minced beef patties.',
    longDescription: 'Originating from Peshawar, these flat, round kebabs are made from minced beef, mixed with tomatoes, onions, and coarse spices, then pan-fried to create a crispy exterior and soft interior.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2017/02/DSC_0019-1.jpg',
    aiHint: 'chapli kabab',
    price: 230,
    ingredients: ['Minced Beef', 'Tomato', 'Onion', 'Pomegranate Seeds', 'Spices'],
    category: 'BBQ',
    reviews: [],
  },
   // Breads & Sides
  {
    id: 34,
    slug: 'roti-naan',
    name: 'Roti / Naan',
    description: 'Plain tandoori roti or naan.',
    longDescription: 'Choose between a simple whole wheat Roti or a soft, leavened Naan, both baked fresh in our tandoor.',
    image: 'https://images.pexels.com/photos/2471171/pexels-photo-2471171.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'roti naan',
    price: 30,
    ingredients: ["Flour", "Water", "Yeast"],
    category: "Breads",
    reviews: [],
  },
  {
    id: 35,
    slug: 'roghni-naan',
    name: 'Roghni Naan',
    description: 'Rich, soft naan brushed with butter.',
    longDescription: 'Roghni Naan is a richer version of the classic naan, enriched with milk and yogurt, brushed with butter (roghan) and topped with sesame seeds before baking.',
    image: 'https://www.foodfusion.com/wp-content/uploads/2019/04/Roghni-Naan-Recipe-by-Food-Fusion-1.jpg',
    aiHint: 'roghni naan',
    price: 60,
    ingredients: ['Flour', 'Milk', 'Yogurt', 'Butter', 'Sesame Seeds'],
    category: 'Breads',
    reviews: [],
  },
  {
    id: 36,
    slug: 'raita-chatni',
    name: 'Raita / Chatni',
    description: 'A single serving of yogurt dip or chutney.',
    longDescription: 'A refreshing side of yogurt raita or tangy chutney to complement your meal. One serving.',
    image: 'https://www.kfoods.com/images1/newrecipeicon/pudina-raita_362.jpg',
    aiHint: 'raita chutney',
    price: 50,
    ingredients: ["Yogurt", "Mint", "Spices", "Tamarind"],
    category: "Sides",
    reviews: [],
  },
  {
    id: 37,
    slug: 'salad-mix',
    name: 'Salad Mix (Single)',
    description: 'A single serving of fresh mixed salad.',
    longDescription: 'A fresh, crisp salad with seasonal vegetables like cucumber, tomatoes, onions, and lettuce. A healthy addition to any meal.',
    image: 'https://images.pexels.com/photos/406152/pexels-photo-406152.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'fresh salad',
    price: 50,
    ingredients: ["Cucumber", "Tomato", "Onion", "Lettuce"],
    category: "Sides",
    reviews: [],
  },
  {
    id: 38,
    slug: 'soft-drink',
    name: 'Soft Drink (1.5L)',
    description: '1.5L bottle of your favorite soft drink.',
    longDescription: 'Choose from Coke, 7up, Big Apple, Leechi, Sprite, or Cola Next. The perfect way to complete your feast.',
    image: 'https://images.pexels.com/photos/7404740/pexels-photo-7404740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    aiHint: 'soft drinks',
    price: 220,
    ingredients: ["Carbonated Water", "Sugar", "Flavoring"],
    category: "Sides",
    reviews: [],
  },
];

export const todaysSpecialDishes: Dish[] = [
  {
    id: 101,
    slug: "goat-paye-full",
    name: "Goat Paye (Full Dozen)",
    description: "A dozen goat trotters, slow-cooked overnight.",
    longDescription: "A true delicacy, goat trotters are slow-cooked overnight with a blend of aromatic spices to create a rich, gelatinous, and deeply flavorful stew. Served as a dozen.",
    image: "https://www.foodfusion.com/wp-content/uploads/2019/11/Mutton-Paya-Recipe-by-Food-Fusion-1.jpg",
    aiHint: "goat paye",
    price: 3600,
    ingredients: ["Goat Trotters", "Onion", "Ginger", "Garlic", "Spices"],
    category: "Special Orders",
    reviews: [],
  },
  {
    id: 102,
    slug: "goat-paye-half",
    name: "Goat Paye (Half Dozen)",
    description: "Half a dozen goat trotters, slow-cooked overnight.",
    longDescription: "A true delicacy, goat trotters are slow-cooked overnight with a blend of aromatic spices to create a rich, gelatinous, and deeply flavorful stew. Served as a half-dozen.",
    image: "https://www.kfoods.com/images1/newrecipeicon/mutton-paye_50.jpg",
    aiHint: "goat paye plate",
    price: 2000,
    ingredients: ["Goat Trotters", "Onion", "Ginger", "Garlic", "Spices"],
    category: "Special Orders",
    reviews: [],
  },
  {
    id: 103,
    slug: "beef-paye-full",
    name: "Beef Paye (2 Paya)",
    description: "Two beef trotters, slow-cooked overnight.",
    longDescription: "A hearty and robust dish of two beef trotters, slow-cooked overnight to tender perfection in a spicy, flavorful stew. Unavailable on Wednesday & Thursday.",
    image: "https://i.ytimg.com/vi/bNw4bVq22FA/maxresdefault.jpg",
    aiHint: "beef paye",
    price: 4800,
    ingredients: ["Beef Trotters", "Onion", "Ginger", "Garlic", "Spices"],
    category: "Special Orders",
    reviews: [],
  },
  {
    id: 104,
    slug: "beef-paye-half",
    name: "Beef Paye (1 Paya)",
    description: "One beef trotter, slow-cooked overnight.",
    longDescription: "A single beef trotter, slow-cooked overnight to tender perfection in a spicy, flavorful stew. Unavailable on Wednesday & Thursday.",
    image: "https://www.masala.tv/wp-content/uploads/2019/10/Beef-Paya-Recipe.jpg",
    aiHint: "beef paye plate",
    price: 2600,
    ingredients: ["Beef Trotters", "Onion", "Ginger", "Garlic", "Spices"],
    category: "Special Orders",
    reviews: [],
  },
  {
    id: 105,
    slug: "nihari-bong",
    name: "Nihari / Bong with Nalli (per kg)",
    description: "Slow-cooked beef stew, priced per kg of raw meat.",
    longDescription: "A legendary slow-cooked beef shank (nihari) stew with rich bone marrow (nalli). Minimum order of 3kg. Unavailable on Wednesday & Thursday.",
    image: "https://www.foodfusion.com/wp-content/uploads/2021/01/beef-nihari.jpg",
    aiHint: "nihari beef",
    price: 2000,
    ingredients: ["Beef Shank", "Bone Marrow", "Flour", "Nihari Masala"],
    category: "Special Orders",
    reviews: [],
  },
  {
    id: 106,
    slug: "special-raita",
    name: "Special Raita (per kg)",
    description: "Thick and creamy yogurt raita.",
    longDescription: "1kg of our special, thick and creamy raita made with mint or zeera, without adding any water. The perfect cooling accompaniment.",
    image: "https://www.kfoods.com/images1/newrecipeicon/zeera-raita_363.jpg",
    aiHint: "yogurt raita",
    price: 550,
    ingredients: ["Yogurt", "Mint", "Cumin", "Salt"],
    category: "Special Orders",
    reviews: [],
  },
  // Daigs
  {
    id: 201,
    slug: "biryani-daig-1",
    name: "Biryani Daig (10+5)",
    description: "10kg Rice + 5kg Chicken. No necks.",
    longDescription: "A full daig of special biryani with 10kg of rice and 5kg of chicken (no necks included). Perfect for large gatherings.",
    image: "https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    aiHint: "biryani daig",
    price: 18000,
    ingredients: ["Basmati Rice", "Chicken", "Biryani Masala", "Yogurt"],
    category: "Daig",
    reviews: [],
  },
  {
    id: 202,
    slug: "biryani-daig-2",
    name: "Biryani Daig (10+10)",
    description: "10kg Rice + 10kg Chicken. No necks.",
    longDescription: "An extra-large daig of special biryani with 10kg of rice and 10kg of chicken (no necks included). For when you need to feed a crowd.",
    image: "https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    aiHint: "large biryani daig",
    price: 24000,
    ingredients: ["Basmati Rice", "Chicken", "Biryani Masala", "Yogurt"],
    category: "Daig",
    reviews: [],
  },
  {
    id: 203,
    slug: "korma-daig",
    name: "Murgh Korma Daig (10kg)",
    description: "10kg of rich Chicken Korma. No necks.",
    longDescription: "A full 10kg daig of our luxurious chicken korma (no necks included). A rich, creamy, and flavorful centerpiece for any event.",
    image: "https://www.foodfusion.com/wp-content/uploads/2019/12/Chicken-Korma-Recipe-by-Food-Fusion-1.jpg",
    aiHint: "korma daig",
    price: 18000,
    ingredients: ["Chicken", "Yogurt", "Fried Onions", "Spices"],
    category: "Daig",
    reviews: [],
  },
  {
    id: 204,
    slug: "pulao-daig-1",
    name: "Murgh Pulao Daig (10+5)",
    description: "10kg Rice + 5kg Chicken. No necks.",
    longDescription: "A full daig of our aromatic chicken pulao with 10kg of rice and 5kg of chicken (no necks included).",
    image: "https://www.foodfusion.com/wp-content/uploads/2019/08/Chicken-Pulao-Recipe-by-Food-Fusion-1.jpg",
    aiHint: "pulao daig",
    price: 18000,
    ingredients: ["Basmati Rice", "Chicken", "Whole Spices", "Onion"],
    category: "Daig",
    reviews: [],
  },
  {
    id: 205,
    slug: "pulao-daig-2",
    name: "Murgh Pulao Daig (10+10)",
    description: "10kg Rice + 10kg Chicken. No necks.",
    longDescription: "An extra-large daig of our aromatic chicken pulao with 10kg of rice and 10kg of chicken (no necks included).",
    image: "https://images.pexels.com/photos/7394140/pexels-photo-7394140.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    aiHint: "large pulao daig",
    price: 24000,
    ingredients: ["Basmati Rice", "Chicken", "Whole Spices", "Onion"],
    category: "Daig",
    reviews: [],
  },
  {
    id: 206,
    slug: "karahi-daig",
    name: "Chicken Karahi Daig (10kg)",
    description: "10kg of spicy Chicken Karahi. No necks.",
    longDescription: "A full 10kg daig of our spicy and tangy chicken karahi (no necks included). Cooked fresh in a giant wok.",
    image: "https://images.pexels.com/photos/20860408/pexels-photo-20860408/free-photo-of-a-bowl-of-chicken-curry-with-a-lime-on-the-side.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    aiHint: "karahi daig",
    price: 18000,
    ingredients: ["Chicken", "Tomatoes", "Green Chilies", "Spices"],
    category: "Daig",
    reviews: [],
  },
  {
    id: 207,
    slug: "halwa-suji-daig",
    name: "Suji Halwa Daig (4kg)",
    description: "4kg of special Suji Halwa with nuts.",
    longDescription: "A minimum order of 4kg of our special suji halwa, prepared with almonds, cashews, coconut, raisins, and dates. A perfect sweet dish.",
    image: "https://www.foodfusion.com/wp-content/uploads/2019/01/Suji-Halwa-1.jpg",
    aiHint: "suji halwa",
    price: 5800,
    ingredients: ["Semolina", "Sugar", "Ghee", "Nuts", "Dates"],
    category: "Daig",
    reviews: [],
  }
];
