export type Review = {
  id: number;
  name: string;
  avatar: string;
  rating: number;
  text: string;
};

export type Dish = {
  id: number;
  slug: string;
  name: string;
  nameUrdu: string;
  description: string;
  longDescription: string;
  image: string;
  aiHint: string;
  price: number;
  ingredients: string[];
  category?: string;
  reviews: Review[];
};

export const dishes: Dish[] = [
  // BBQ
  {
    id: 5,
    slug: 'chicken-leg-tikka',
    name: 'Chicken Leg Tikka',
    nameUrdu: 'چکن لیگ تکا',
    description: 'Juicy chicken leg marinated in traditional spices and grilled to perfection.',
    longDescription: 'A classic BBQ favorite, our Chicken Leg Tikka features a whole chicken leg marinated in a blend of yogurt, lemon juice, and aromatic spices, then grilled over charcoal for a smoky flavor.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken tikka leg',
    price: 600.00,
    ingredients: ['Chicken Leg', 'Yogurt', 'Tikka Masala', 'Lemon Juice', 'Ginger-Garlic Paste'],
    category: 'BBQ',
    reviews: [],
  },
  {
    id: 6,
    slug: 'chicken-chest-tikka',
    name: 'Chicken Chest Tikka',
    nameUrdu: 'چکن چیسٹ تکا',
    description: 'Tender chicken breast piece, marinated and grilled.',
    longDescription: 'A lighter but equally delicious option, the Chicken Chest Tikka is a boneless breast piece marinated in our signature spice mix and grilled until tender and flavorful.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken tikka breast',
    price: 650.00,
    ingredients: ['Chicken Breast', 'Yogurt', 'Tikka Masala', 'Lemon Juice', 'Spices'],
    category: 'BBQ',
    reviews: [],
  },
  {
    id: 7,
    slug: 'tikka-boti',
    name: 'Tikka Boti (6 pcs)',
    nameUrdu: 'تکہ بوٹی',
    description: 'Boneless chicken cubes marinated in spicy tikka masala.',
    longDescription: 'Six succulent pieces of boneless chicken marinated in a fiery red tikka masala, skewered and grilled over open flames. A perfect appetizer to start your meal.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tikka boti',
    price: 700.00,
    ingredients: ['Boneless Chicken', 'Tikka Masala', 'Yogurt', 'Spices'],
    category: 'BBQ',
    reviews: [],
  },
  {
    id: 8,
    slug: 'malai-boti',
    name: 'Malai Boti (6 pcs)',
    nameUrdu: 'ملائی بوٹی',
    description: 'Creamy, melt-in-your-mouth chicken cubes.',
    longDescription: 'Six pieces of boneless chicken marinated in a rich mixture of cream (malai), cheese, and mild spices, resulting in an incredibly tender and flavorful BBQ dish.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'malai boti',
    price: 750.00,
    ingredients: ['Boneless Chicken', 'Fresh Cream', 'Cheese', 'White Pepper', 'Cardamom'],
    category: 'BBQ',
    reviews: [],
  },
  {
    id: 9,
    slug: 'seekh-kabab',
    name: 'Seekh Kabab',
    nameUrdu: 'سیخ کباب',
    description: 'Minced meat kebabs, spiced and grilled on skewers.',
    longDescription: 'Minced chicken or mutton, mixed with onions, herbs, and a special blend of spices, molded onto skewers (seekh) and grilled to perfection. A juicy and aromatic delight.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'seekh kabab',
    price: 550.00,
    ingredients: ['Minced Meat', 'Onion', 'Coriander', 'Mint', 'Spices'],
    category: 'BBQ',
    reviews: [],
  },
  {
    id: 10,
    slug: 'chapli-kabab',
    name: 'Chapli Kabab',
    nameUrdu: 'چپلی کباب',
    description: 'Peshawari-style flat minced meat patties.',
    longDescription: 'Originating from Peshawar, these flat, round kebabs are made from minced beef or chicken, mixed with tomatoes, onions, and coarse spices, then pan-fried to create a crispy exterior and soft interior.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chapli kabab',
    price: 400.00,
    ingredients: ['Minced Beef', 'Tomato', 'Onion', 'Pomegranate Seeds', 'Spices'],
    category: 'BBQ',
    reviews: [],
  },

  // Karahi
  {
    id: 1,
    slug: "chicken-karahi",
    name: "Chicken Karahi",
    nameUrdu: "چکن کڑاہی",
    description:
      "A rich and spicy chicken curry cooked in a traditional karahi (wok).",
    longDescription:
      "A classic Pakistani dish, Chicken Karahi is known for its robust and spicy flavor, cooked with tomatoes, ginger, garlic, and green chilies in a traditional wok-like pan called a karahi. It's a staple in Pakistani households and restaurants alike, loved for its simple yet profound taste.",
    image: "https://placehold.co/600x400.png",
    aiHint: "chicken karahi",
    price: 1250.00,
    ingredients: [
      "Chicken",
      "Tomatoes",
      "Ginger",
      "Garlic",
      "Green Chilies",
      "Coriander",
      "Spices",
    ],
    category: "Karahi",
    reviews: [
      {
        id: 1,
        name: "Ahmed Khan",
        avatar: "https://placehold.co/40x40.png",
        rating: 5,
        text: "The best chicken karahi I've had outside of Pakistan! Perfectly spiced.",
      },
      {
        id: 2,
        name: "Fatima Ali",
        avatar: "https://placehold.co/40x40.png",
        rating: 4,
        text: "Very delicious and authentic. Could be a little less oily, but the taste was superb.",
      },
    ],
  },
  {
    id: 11,
    slug: 'beef-karahi',
    name: 'Beef Karahi',
    nameUrdu: 'بیف کڑاہی',
    description: 'Tender beef cooked in a spicy tomato and ginger gravy.',
    longDescription: 'Succulent pieces of beef slow-cooked in a rich and aromatic gravy of tomatoes, ginger, garlic, and traditional karahi spices. A hearty and satisfying dish.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'beef karahi',
    price: 1600.00,
    ingredients: ['Beef', 'Tomatoes', 'Ginger', 'Yogurt', 'Spices'],
    category: 'Karahi',
    reviews: [],
  },
  {
    id: 12,
    slug: 'mutton-karahi',
    name: 'Mutton Karahi',
    nameUrdu: 'مٹن کڑاہی',
    description: 'Flavorful mutton curry, a true Lahori delight.',
    longDescription: 'A delicacy in Pakistani cuisine, Mutton Karahi is prepared with tender mutton pieces cooked in a wok with tomatoes, green chilies, and a blend of fragrant spices.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'mutton karahi',
    price: 2200.00,
    ingredients: ['Mutton', 'Tomatoes', 'Green Chilies', 'Black Pepper', 'Coriander'],
    category: 'Karahi',
    reviews: [],
  },
  
  // Rice
  {
    id: 2,
    slug: "beef-biryani",
    name: "Beef Biryani",
    nameUrdu: "بیف بریانی",
    description:
      "Fragrant basmati rice cooked with tender beef and aromatic spices.",
    longDescription:
      "Beef Biryani is a celebratory dish made with layers of fragrant basmati rice, tender, marinated beef, and a blend of aromatic spices like saffron, cardamom, and cloves. Garnished with fried onions and fresh herbs, it's a complete meal that's both hearty and incredibly flavorful.",
    image: "https://placehold.co/600x400.png",
    aiHint: "beef biryani",
    price: 1500.00,
    ingredients: [
      "Basmati Rice",
      "Beef",
      "Yogurt",
      "Onions",
      "Saffron",
      "Aromatic Spices",
      "Mint",
    ],
    category: "Rice",
    reviews: [
      {
        id: 1,
        name: "Usman Tariq",
        avatar: "https://placehold.co/40x40.png",
        rating: 5,
        text: "Absolutely phenomenal biryani. The beef was so tender and the rice was perfectly cooked.",
      },
    ],
  },
  {
    id: 13,
    slug: 'chicken-pulao',
    name: 'Chicken Pulao',
    nameUrdu: 'چکن پلاؤ',
    description: 'Aromatic rice and chicken cooked in a savory broth.',
    longDescription: 'A subtly flavored yet delicious one-pot meal where basmati rice is cooked in a seasoned chicken broth, creating a fragrant and wholesome dish.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken pulao',
    price: 900.00,
    ingredients: ['Chicken', 'Basmati Rice', 'Whole Spices', 'Onion', 'Yogurt'],
    category: 'Rice',
    reviews: [],
  },
  {
    id: 14,
    slug: 'beef-pulao',
    name: 'Beef Pulao',
    nameUrdu: 'بیف پلاؤ',
    description: 'Hearty and flavorful rice cooked with tender beef.',
    longDescription: 'A traditional rice dish where tender beef and basmati rice are cooked together in a broth of aromatic spices, creating a rich and savory meal.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'beef pulao',
    price: 1100.00,
    ingredients: ['Beef', 'Basmati Rice', 'Onion', 'Ginger-Garlic', 'Whole Spices'],
    category: 'Rice',
    reviews: [],
  },
  {
    id: 15,
    slug: 'matar-pulao',
    name: 'Matar Pulao',
    nameUrdu: 'مٹر پلاؤ',
    description: 'Basmati rice cooked with green peas and mild spices.',
    longDescription: 'A simple yet delightful vegetarian rice dish, Matar Pulao (Pea Pilaf) is made with fragrant basmati rice, sweet green peas, and whole spices.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'matar pulao peas',
    price: 600.00,
    ingredients: ['Basmati Rice', 'Green Peas', 'Onion', 'Cumin', 'Ghee'],
    category: 'Rice',
    reviews: [],
  },
  {
    id: 16,
    slug: 'chicken-biryani',
    name: 'Chicken Biryani',
    nameUrdu: 'چکن بریانی',
    description: 'The king of all rice dishes, layered and aromatic.',
    longDescription: 'A world-renowned dish, our Chicken Biryani is made with layers of spicy marinated chicken and fragrant saffron-infused basmati rice, cooked to perfection with herbs and fried onions.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken biryani',
    price: 1350.00,
    ingredients: ['Chicken', 'Basmati Rice', 'Yogurt', 'Biryani Masala', 'Saffron'],
    category: 'Rice',
    reviews: [],
  },

  // Breads
  {
    id: 17,
    slug: 'naan',
    name: 'Naan',
    nameUrdu: 'نان',
    description: 'Soft and fluffy leavened bread from the tandoor.',
    longDescription: 'A classic flatbread, our Naan is baked in a traditional clay oven (tandoor), resulting in a soft, chewy texture perfect for soaking up curries.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'naan bread',
    price: 50.00,
    ingredients: ['Flour', 'Yogurt', 'Yeast', 'Milk'],
    category: 'Breads',
    reviews: [],
  },
  {
    id: 18,
    slug: 'roti',
    name: 'Roti',
    nameUrdu: 'روٹی',
    description: 'Whole wheat unleavened flatbread.',
    longDescription: 'A staple in every Pakistani meal, this is a simple, unleavened flatbread made from whole wheat flour, cooked on a tawa (griddle).',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'roti bread',
    price: 40.00,
    ingredients: ['Whole Wheat Flour', 'Water', 'Salt'],
    category: 'Breads',
    reviews: [],
  },
  {
    id: 19,
    slug: 'rogni-naan',
    name: 'Roghni Naan',
    nameUrdu: 'روغنی نان',
    description: 'Rich, soft naan bread brushed with butter and sesame seeds.',
    longDescription: 'Roghni Naan is a richer version of the classic naan, enriched with milk and yogurt, brushed with butter (roghan) and topped with sesame seeds before baking.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'roghni naan',
    price: 80.00,
    ingredients: ['Flour', 'Milk', 'Yogurt', 'Butter', 'Sesame Seeds'],
    category: 'Breads',
    reviews: [],
  },
  {
    id: 20,
    slug: 'afghani-naan',
    name: 'Afghani Naan',
    nameUrdu: 'افغانی نان',
    description: 'Large, soft, and slightly sweet naan.',
    longDescription: 'A large, oval-shaped flatbread that is soft and slightly chewy. It\'s a staple of Afghan cuisine and pairs wonderfully with grilled meats.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'afghani bread',
    price: 100.00,
    ingredients: ['Flour', 'Yeast', 'Milk', 'Sugar'],
    category: 'Breads',
    reviews: [],
  },
  {
    id: 21,
    slug: 'tandoori-paratha',
    name: 'Tandoori Paratha',
    nameUrdu: 'تندوری پراٹھا',
    description: 'Crispy, flaky layered bread from the tandoor.',
    longDescription: 'A multi-layered whole wheat bread, cooked in the tandoor to give it a unique crispy yet flaky texture. A treat for bread lovers.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tandoori paratha',
    price: 120.00,
    ingredients: ['Whole Wheat Flour', 'Butter', 'Salt'],
    category: 'Breads',
    reviews: [],
  },
  {
    id: 22,
    slug: 'alu-naan',
    name: 'Alu Naan',
    nameUrdu: 'آلو نان',
    description: 'Naan stuffed with a spiced potato filling.',
    longDescription: 'A soft naan bread with a delicious and savory filling of spiced mashed potatoes, herbs, and onions. A meal in itself!',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'potato naan',
    price: 150.00,
    ingredients: ['Flour', 'Potato', 'Onion', 'Coriander', 'Spices'],
    category: 'Breads',
    reviews: [],
  },
  {
    id: 23,
    slug: 'keema-naan',
    name: 'Keema Naan',
    nameUrdu: 'قیمہ نان',
    description: 'Naan stuffed with spicy minced meat.',
    longDescription: 'A hearty and flavorful flatbread, Keema Naan is stuffed with a savory mixture of spicy minced meat (chicken or mutton) and baked to perfection.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'keema naan',
    price: 250.00,
    ingredients: ['Flour', 'Minced Meat', 'Onion', 'Ginger-Garlic', 'Spices'],
    category: 'Breads',
    reviews: [],
  },
  
  // Chinese
  {
    id: 24,
    slug: 'chicken-chili-dry',
    name: 'Chicken Chili Dry',
    nameUrdu: 'چکن چلی ڈرائی',
    description: 'Spicy stir-fried chicken with green chilies and onions.',
    longDescription: 'A popular Pakistani-Chinese dish, featuring bite-sized pieces of chicken stir-fried with green chilies, onions, and bell peppers in a spicy soy-based sauce.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken chili dry',
    price: 1100.00,
    ingredients: ['Boneless Chicken', 'Green Chilies', 'Onion', 'Soy Sauce', 'Vinegar'],
    category: 'Chinese',
    reviews: [],
  },
  {
    id: 25,
    slug: 'chicken-shashlik',
    name: 'Chicken Shashlik',
    nameUrdu: 'چکن شاشلک',
    description: 'Skewered chicken and vegetables in a tangy gravy.',
    longDescription: 'Cubes of chicken, bell peppers, onions, and tomatoes are grilled on skewers and served with a sweet and tangy tomato-based gravy.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken shashlik',
    price: 1150.00,
    ingredients: ['Chicken', 'Bell Peppers', 'Onion', 'Tomato', 'Ketchup'],
    category: 'Chinese',
    reviews: [],
  },
  {
    id: 26,
    slug: 'egg-fried-rice',
    name: 'Egg Fried Rice',
    nameUrdu: 'انڈے فرائیڈ رائس',
    description: 'Classic fried rice with scrambled eggs and vegetables.',
    longDescription: 'A simple yet satisfying dish of stir-fried rice with scrambled eggs, carrots, peas, and a light touch of soy sauce.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'egg fried rice',
    price: 700.00,
    ingredients: ['Rice', 'Eggs', 'Carrots', 'Peas', 'Soy Sauce'],
    category: 'Chinese',
    reviews: [],
  },
  {
    id: 27,
    slug: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    nameUrdu: 'چکن فرائیڈ رائس',
    description: 'Wok-tossed rice with chicken, egg, and vegetables.',
    longDescription: 'A complete meal in a bowl, our Chicken Fried Rice is made with tender chicken pieces, scrambled eggs, and mixed vegetables, all stir-fried with rice and savory sauces.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken fried rice',
    price: 850.00,
    ingredients: ['Rice', 'Chicken', 'Eggs', 'Vegetables', 'Soy Sauce'],
    category: 'Chinese',
    reviews: [],
  },
  {
    id: 28,
    slug: 'chicken-manchurian',
    name: 'Chicken Manchurian',
    nameUrdu: 'چکن منچورین',
    description: 'Crispy chicken in a sweet and tangy Manchurian sauce.',
    longDescription: 'A famous Indo-Chinese dish, featuring crispy fried chicken pieces tossed in a flavorful sauce that is a perfect balance of sweet, tangy, and savory notes.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken manchurian',
    price: 1200.00,
    ingredients: ['Chicken', 'Corn Flour', 'Soy Sauce', 'Ketchup', 'Vinegar'],
    category: 'Chinese',
    reviews: [],
  },
  {
    id: 29,
    slug: 'chicken-chow-mein',
    name: 'Chicken Chow Mein',
    nameUrdu: 'چکن چاؤمین',
    description: 'Stir-fried noodles with chicken and vegetables.',
    longDescription: 'A classic noodle dish with stir-fried egg noodles, tender chicken strips, and a variety of vegetables like cabbage, carrots, and bell peppers in a savory sauce.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken chow mein',
    price: 950.00,
    ingredients: ['Noodles', 'Chicken', 'Cabbage', 'Carrots', 'Soy Sauce'],
    category: 'Chinese',
    reviews: [],
  },

  // Traditional Curries
  {
    id: 30,
    slug: 'palak-gosht',
    name: 'Palak Gosht',
    nameUrdu: 'پالک گوشت',
    description: 'A nutritious curry of spinach and meat.',
    longDescription: 'A wholesome and traditional curry made with fresh spinach (palak) and tender meat (gosht), slow-cooked with aromatic spices until the flavors meld together beautifully.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'palak gosht spinach',
    price: 1000.00,
    ingredients: ['Mutton/Chicken', 'Spinach', 'Onion', 'Tomato', 'Spices'],
    category: 'Curry',
    reviews: [],
  },
  {
    id: 31,
    slug: 'aloo-bhujia',
    name: 'Aloo ki Bhujia',
    nameUrdu: 'آلو کی بھجیا',
    description: 'A simple and flavorful dry potato curry.',
    longDescription: 'A humble yet delicious dish of diced potatoes cooked with onions, tomatoes, and a handful of spices. A perfect comfort food.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'potato curry',
    price: 500.00,
    ingredients: ['Potatoes', 'Onion', 'Tomato', 'Turmeric', 'Cumin Seeds'],
    category: 'Curry',
    reviews: [],
  },
  {
    id: 32,
    slug: 'daal-makhani',
    name: 'Daal Makhani',
    nameUrdu: 'دال مکھنی',
    description: 'Creamy and buttery black lentil curry.',
    longDescription: 'A rich and decadent lentil dish made from black lentils and kidney beans, slow-cooked in a tomato-based sauce with butter and cream. A Punjabi specialty.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'daal makhani lentil',
    price: 800.00,
    ingredients: ['Black Lentils', 'Kidney Beans', 'Tomato Puree', 'Butter', 'Cream'],
    category: 'Curry',
    reviews: [],
  },
  {
    id: 33,
    slug: 'butter-chicken',
    name: 'Butter Chicken',
    nameUrdu: 'بٹر چکن',
    description: 'Grilled chicken in a smooth, buttery tomato gravy.',
    longDescription: 'One of the most popular curries worldwide, Butter Chicken features tandoori chicken pieces simmered in a mildly spiced, creamy tomato gravy. An indulgent and irresistible dish.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'butter chicken',
    price: 1400.00,
    ingredients: ['Chicken Tikka', 'Tomato Puree', 'Butter', 'Cream', 'Cashew Paste'],
    category: 'Curry',
    reviews: [],
  },
  
  // Misc
  {
    id: 3,
    slug: "chana-chaat",
    name: "Chana Chaat",
    nameUrdu: "چنا چاٹ",
    description: "A refreshing and tangy chickpea salad with spices and chutneys.",
    longDescription:
      "Chana Chaat is a popular Pakistani street food snack. It's a vibrant and refreshing salad made with boiled chickpeas, potatoes, onions, and tomatoes, tossed in a mix of spices and tangy tamarind chutney. It's the perfect light meal or appetizer.",
    image: "https://placehold.co/600x400.png",
    aiHint: "chana chaat",
    price: 450.00,
    ingredients: [
      "Chickpeas",
      "Potatoes",
      "Onion",
      "Tomato",
      "Tamarind Chutney",
      "Yogurt",
      "Spices",
    ],
    category: "Appetizer",
    reviews: [],
  },
  {
    id: 4,
    slug: "samosa",
    name: "Samosa",
    nameUrdu: "سموسہ",
    description: "Crispy pastry filled with spiced potatoes, peas, and minced meat.",
    longDescription:
      "A beloved snack across South Asia, the samosa is a fried or baked pastry with a savory filling, such as spiced potatoes, onions, peas, or minced meat. Its triangular shape is iconic, and it's often served with a side of mint or tamarind chutney.",
    image: "https://placehold.co/600x400.png",
    aiHint: "samosas",
    price: 300.00,
    ingredients: ["Potatoes", "Peas", "Spices", "Flour Pastry", "Minced Meat (optional)"],
    category: "Appetizer",
    reviews: [
      {
        id: 1,
        name: "Ayesha Malik",
        avatar: "https://placehold.co/40x40.png",
        rating: 5,
        text: "Crispy, hot, and perfectly filled. The chutneys were amazing too!",
      },
    ],
  },
  {
    id: 34,
    slug: 'chicken-corn-soup',
    name: 'Chicken Corn Soup',
    nameUrdu: 'چکن کارن سوپ',
    description: 'A hearty and comforting soup with chicken and sweet corn.',
    longDescription: 'A classic comfort soup, made with shredded chicken, sweet corn kernels, and egg ribbons in a thick, savory broth. Perfect for a cold day.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chicken corn soup',
    price: 450.00,
    ingredients: ['Chicken', 'Sweet Corn', 'Egg', 'Chicken Broth', 'Soy Sauce'],
    category: 'Soup',
    reviews: [],
  },
];

export const todaysSpecialDishes: Dish[] = [
  {
    id: 101,
    slug: "sheer-khurma",
    name: "Sheer Khurma",
    nameUrdu: "شیر خورمہ",
    description:
      "A rich vermicelli pudding made with milk, dates, and nuts.",
    longDescription:
      "Sheer Khurma is a traditional festive breakfast and dessert for celebrations. It's a rich and creamy vermicelli pudding made with milk, sweetened with sugar, and flavored with dates, pistachios, almonds, and saffron. It's a dish that symbolizes joy and togetherness.",
    image: "https://placehold.co/600x400.png",
    aiHint: "sheer khurma",
    price: 750.00,
    ingredients: ["Vermicelli", "Milk", "Sugar", "Dates", "Pistachios", "Almonds", "Saffron"],
    category: "Dessert",
    reviews: [
      {
        id: 1,
        name: "Hassan Raza",
        avatar: "https://placehold.co/40x40.png",
        rating: 5,
        text: "Just like my mother makes it for Eid. Brought back so many memories. Delicious!",
      },
    ],
  },
  {
    id: 102,
    slug: "mutton-korma",
    name: "Mutton Korma",
    nameUrdu: "مٹن قورمہ",
    description:
      "A luxurious mutton curry with a yogurt and spice-based sauce.",
    longDescription:
      "Mutton Korma is a quintessential celebratory dish. Tender pieces of mutton are slow-cooked in a creamy, fragrant sauce made from yogurt, fried onions, and a delicate blend of whole and ground spices. The result is a rich, aromatic curry with a velvety texture that pairs perfectly with naan or rice.",
    image: "https://placehold.co/600x400.png",
    aiHint: "mutton korma",
    price: 1800.00,
    ingredients: [
      "Mutton",
      "Yogurt",
      "Onions",
      "Ginger-Garlic Paste",
      "Whole Spices",
      "Kewra Water",
    ],
    category: "Curry",
    reviews: [
      {
        id: 1,
        name: "Zainab Iqbal",
        avatar: "https://placehold.co/40x40.png",
        rating: 5,
        text: "The korma was out of this world! So rich and flavorful, the mutton just melted in my mouth.",
      },
    ],
  },
];
